### ISSUE TITLE
Output of `pokego -h` in `README.md` does not align with actual output of `pokego -h`

### ISSUE THREAD

**Issue by jameskim0987** [rubiin/pokego#12]
### Describe the bug

Output of `pokego -h` in `README.md` does not align with actual output of `pokego -h`. It looks like a misalignment where we need to align the prompts to match the output outlined in `README.md`

actual output of `pokego -h`:
```
$ pokego -h
USAGE:  -form string
        Show an alternate form of a pokemon
  -list
        Print list of all pokemon
  -name string
        Select pokemon by name
  -no-title
        Do not display pokemon name
  -random string
        Show a random pokemon. This flag can optionally be followed by a generation number or range (default "1-8")
  -shiny
        Show the shiny version of the pokemon instead
  -version
        Show the cli version
```

### Reproduction

run `pokego -h` and compare

### System Info

```Shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/rubiin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/rubiin/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rubiin** [comment]
PR welcome
