### ISSUE TITLE
feat: completions

### ISSUE THREAD

**Issue by rubiin** [rubiin/pokego#5]
### Clear and concise description of the problem

Generate shell completions using complgen

### Suggested solution

Use [complgen](https://github.com/adaszko/complgen)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/rubiin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/rubiin/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jameskim0987** [comment]
Hi @rubiin, I can have a look at this issue.

**Comment by rubiin** [comment]
@jameskim0987 go for it

**Comment by jameskim0987** [comment]
@rubiin Unfortunately, I'm having some issues on my local environment to get `complgen` working, so I opened these issues in their repo: 
1. https://github.com/adaszko/complgen/issues/55
2. https://github.com/adaszko/complgen/issues/56

Until I get some insight on those, my progress might remain paused so if other wants to take this up I leave it up to them.

**Comment by rubiin** [comment]
@jameskim0987 No worries. Take your time.
